# Generated by Django 5.0.3 on 2024-04-20 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("httpapitest", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("module_name", models.CharField(max_length=50, verbose_name="模块名称")),
                ("test_user", models.CharField(max_length=50, verbose_name="测试负责人")),
                (
                    "simple_desc",
                    models.CharField(max_length=100, null=True, verbose_name="简要描述"),
                ),
                (
                    "other_desc",
                    models.CharField(max_length=100, null=True, verbose_name="其他信息"),
                ),
                (
                    "belong_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="httpapitest.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "模块信息",
                "db_table": "ModuleInfo",
            },
        ),
    ]
