# Generated by Django 2.2.7 on 2020-01-11 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('httpapitest', '0006_testconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=50, verbose_name='用例名称')),
                ('belong_project', models.CharField(max_length=50, verbose_name='所属项目')),
                ('include', models.CharField(max_length=1024, null=True, verbose_name='前置config/test')),
                ('author', models.CharField(max_length=20, verbose_name='创建者')),
                ('request', models.TextField(verbose_name='请求信息')),
                ('belong_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='httpapitest.Module')),
            ],
            options={
                'verbose_name': '用例信息',
                'db_table': 'TestCaseInfo',
            },
        ),
    ]
