# Generated by Django 2.2.7 on 2020-01-04 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('httpapitest', '0003_module'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DebugTalk',
        ),
    ]
